### ISSUE TITLE
go get errors

### ISSUE THREAD

**Issue by alejandrox1** [rhysd/dot-github#2]
I tried installing this package following the instructions in the `README.md`, using `go get dot-github`, but this returned a couple error message.

### Actual Behavior
```
 $ go get github.com/rhysd/dot-github
# github.com/rhysd/go-github-selfupdate/selfupdate
go/src/github.com/rhysd/go-github-selfupdate/selfupdate/detect.go:145:14: cannot use asset.GetID() (type int) as type int64 in field value
go/src/github.com/rhysd/go-github-selfupdate/selfupdate/update.go:59:111: cannot use rel.AssetID (type int64) as type int in argument to up.api.Repositories.DownloadReleaseAsset
```

### Your Environment

- OS: Ubuntu 18.04 LTS
- GO version: go1.10.1 linux/amd64
- dot-github version: v1.3.0

**Comment by rhysd** [comment]
Please reinstall google/go-github. I think your local go-github installation is old. Previously, go-github utilized `int` for ID, then it changed the type to `int64`.
I guess `go  get -u github.com/rhysd/dot-github` would successfully perform installation.

**Comment by rhysd** [comment]
No response.
